### ISSUE TITLE
Architecture frontend - composants carto

### ISSUE THREAD

**Issue by TheoLechemia** [PnX-SI/gn_module_flore_prioritaire#14]
Le choix avait été fait de garder le même composant cartographique entre les interface de visualisation et de saisie des AP. Seule la partie droite de l'écran bougeait via un sous-routing.
Cette architecture pose des gros conflits sur la carto et complexifie le code. On doit sans cesse vérifier les changements de routes pour afficher/masquer les outils Leaflet-Draw. Les données se superpose entre le composant geojson qui sert simplement à l'affichage et le composant leafletdraw qui permet l’édition.

Il faut repasser à deux composants distincts qui ont chacun un bloc cartographique pour plus de lisibilité et maintenabilité du code.

**Comment by jpm-cbna** [comment]
Fait dans le commit aa3b75c47402fc1b5d5e6cea416643c06c4b5aad.
Effectivement, cela a bien simplifié le code.
