### ISSUE TITLE
Ajout du MNT (DEM)

### ISSUE THREAD

**Issue by jpm-cbna** [PnX-SI/gn_module_flore_prioritaire#20]
Afin de rendre accessible le calcul automatique des altitudes dans le formulaire de l'AP, il faudrait pouvoir ajouter le DEM à la base de données.

Compléter la documentation du module pour indiquer comment le générer à posteriori.

**Comment by camillemonchicourt** [comment]
On utiliserait le MNT déjà présent dans la BDD de GeoNature, non ?

**Comment by bouttier** [comment]
Pour l’installation du MNT dans GeoNature, voir ici : https://github.com/PnX-SI/GeoNature/blob/20f5a9b8340b5d7e6f6070f8abf0d2a673f3fb52/install/03_create_db.sh#L134

**Comment by jpm-cbna** [comment]
La doc d'installation a été complété pour indiquer les 2 commandes Alembic utilisables pour  générer le MNT Raster et Vector:
```bash
# MNT raster
geonature db upgrade ign_bd_alti@head -x local-srid=<local-srid>

# MNT vecteur
geonature db upgrade ign_bd_alti_vector@head
```

Un bug sur le MNT Raster (voir https://github.com/PnX-SI/GeoNature/issues/2044) nous a obligé à installer le MNT vecteur.
