### ISSUE TITLE
Bugs et améliorations en cours

### ISSUE THREAD

**Issue by richardvergely** [PnX-SI/gn_module_flore_prioritaire#3]
Bugs :

- [x] Bug sur indexzp négatifs
- [x] Possibilité de saisir une AP hors d'une ZP
- [x] Impossibilité de modifier une ZP sans observateur
- [x] Possibilité de saisir un dénombrement max inférieur au dénombrement min
- [x] Possibilité d'accéder au formulaire de saisie avant d'avoir dessiné la ZP/AP (réglage du disabled)
- [x] Absence des observateurs et des noms de commune sur l'info d'une ZP
- [x] Absence des observateurs sur la saisie d'AP
- [x] Bug sur les saisies de cercle
- [x] Bug sur l'altimétrie sur les saisies en polygone ou rectangle.
- [x] Edition d'une ZP

Améliorations et compléments à apporter :

- [x] Calcul de la surface des AP sur le front
- [x] Faire une PR sur affichage de l’extent du module et non celui de Geonature par défaut
- [x] Export / Téléchargement des AP
- [x] ajouter une alerte sur la suppression (ZP et AP) 
- [x] Optimisation de code : listes de ZP_MAP_LIST à trier sur le Backend

**Comment by richardvergely** [comment]
Bugs restants sur le module :

Bug sur indexzp négatifs
Possibilité de saisir une AP hors d'une ZP
Impossibilité de modifier une ZP sans observateur
Possibilité de saisir un dénombrement max inférieur au dénombrement min
Possibilité d'accéder au formulaire de saisie avant d'avoir dessiné la ZP/AP (réglage du disabled)
Bug sur les saisies de cercle
Bug sur l'altimétrie sur les saisies en polygone ou rectangle

Améliorations et compléments à apporter :

Ajout des perturbations potentielles ou effectives (booléen dans cor_ap_perturb)
Faire une PR sur affichage de l’extent du module et non celui de Geonature par défaut
Export / Téléchargement des AP
Faire le CRUVED
Optimisation de code : listes de ZP_MAP_LIST à trier sur le Backend

**Comment by jpm-cbna** [comment]
Le problème des indexzp négatif a été résolu en réindexant toutes les données (ZP et AP) lors de la migration. Les id originaux ont été stockés dans le champ `additional_data`.
