### ISSUE TITLE
1st test module Priority_flora Geonature (LB/NF)

### ISSUE THREAD

**Issue by LeaCBNA** [PnX-SI/gn_module_flore_prioritaire#33]
- [x] **Saisie : pas possible d'écrire des observateurs**
- [x] **Migration des données** : affichages ZP : pour certains taxons les ZP ne s'affichent que sous forme de point (exple : Loeflingia hispanica 6049, Lycopodiella inundata 6112, Liparis loeselii 5281). Les ZP dans l'ancienne version sont ok. Histoire de surface minimum (trop petite) ?
  - Le problème était lié au champ `geom_mixte_3857` utilisé pour la géométrie de la ZP. Ce champ contient une géométrie POINT pour certaines ZP. Utilisation de `the_geom_3857` à la place.Voir ci-dessous la requête SQL de correction.
  - En outre, les triggers mettant à jour les géométries des ZP et AP ont été amélioré pour n'intervenir que si les champs qu'ils remplissent sont NULL. Voir ci-dessous la nouvelle version de ces fonctions en base.**
- [x] **Saisie : l'import de gpx et kml fonctionne mais les points disparaissent quand on veut saisir une géométrie**, en fait il y a un ordre pour procéder, 1 tu sélectionnes pour dessiner un polygone, 2 tu fais apparaitre tes gpx/kml  et tu dessines là ça marche, le hic , dès que tu cliques (genre pour te repositionner, très utile qd tu as pas mal de points et sur tout le TAG, car export généralisé des points gps de ton année) ça active le dessin du polygone, ce n'est pas très pratique, faire dans l'autre sens, 1 se positionner 2 dessiner ? 
  - Le problème est situé à 2 niveaux, dans le module où le paramètre `editMode` des composants `pnx-leaflet-filelayer` doit être mis à `true` et au niveau de GeoNature où les composants `pnx-leaflet-filelayer` et `pnx-leaflet-draw` suppriment tous les deux la couche générée par l'autre... J'ai créé [le ticket #2084](https://github.com/PnX-SI/GeoNature/issues/2084) sur le sujet pour trouver une solution pérenne. En attendant, j'ai patché le module et notre version de GeoNature pour que cela fonctionne avec les commits https://github.com/PnX-SI/GeoNature/commit/069ec00af0b4f74f772b1551c71d436ebf23ae33 et https://github.com/PnX-SI/GeoNature/commit/181205ec7274a6de6c798f164e06eaf661d44611.**
- [x] Filtre organismes : doublon CBNA - CBN Alpin -> Supprimer CBN Alpin (ne marche pas)
  - Nécessite de nettoyer les organismes et utilisateur en doublon via UsersHub une fois l'utilisation unique de Flore Sentinelle mise en place.
- [x] Filtre taxons : doublon nom dans la liste (exple : Loeflingia hispanica = Loeflingia hispanica L., 1753 ET Loeflingie d'Espagne = Loeflingia hispanica L., 1753) -> Supprimer la première option
  - C'est une fonctionnalité. Nous laissons le fonctionnement actuel.
- [x] Formulaire AP :  champ fréquence -> si la méthode choisie est "Transect", l'intitulé du champ "Fréquence estimée en %" doit être renommé en "Fréquence calculée en %".
- [x] Dans l'export et la fiche AP, si aucun comptage afficher "NA" et pas "0" (modif dans export + fiche).
  - Nous affichons "NA" sur la fiche. Pour l'export, les champs `total_min` et `total_max` seront vide. J'ai nettoyé la base pour que les entrées avec `0` soient remplacées par `NULL` quand la nomenclature du comptage correspondait à "`Aucun comptage`". Il y avait déjà beaucoup de cas où nous avions les valeurs `NULL` pour les champs `total_min` et `total_max` mais pas toujours...
- [x] Export : au niveau de la liste des ZP d'une espèce semble bogué (csv et geojson). Au niveau de d'une ZP semble ok. 
  - Finalement, l'export semble à nouveau fonctionnel depuis le bon paramétrage de la liste des observateurs à utiliser dans le module. Vérifier si le problème ne se reproduit plus. **-> Bug toujours présent**

**Comment by jpm-cbna** [comment]
Requête SQL permettant de mettre à jour les géométrie des zones de prospection depuis la version 1 de la base de données.
```sql
BEGIN;

UPDATE pr_priority_flora.t_zprospect SET
  	geom_local = zp1.the_geom_2154,
  	geom_4326 = public.st_transform(zp1.the_geom_3857, 4326),
  	geom_point_4326 = public.st_transform(zp1.geom_point_3857, 4326),
    "area" = public.st_area(zp1.the_geom_2154)
FROM pr_priority_flora.t_zprospect AS zp2
	JOIN migrate_v1_florepatri.t_zprospection AS zp1
		ON zp1.indexzp = CAST(zp2.additional_data-> 'migrateOriginalInfos' ->> 'indexZp' AS BIGINT)
WHERE pr_priority_flora.t_zprospect.id_zp = zp2.id_zp ;

COMMIT;
```

**Comment by jpm-cbna** [comment]
Nouveau fonctions améliorées pour les triggers de mise à jour des géométries des ZP et AP:
```sql
-----------------------------------------------------------------------
-- Fonction Trigger: actualisation champs geom_local et surface
-----------------------------------------------------------------------

CREATE OR REPLACE FUNCTION pr_priority_flora.edit_zp()
  RETURNS trigger AS
$BODY$
BEGIN
  IF (NEW.geom_local IS NULL) THEN
    NEW.geom_local = public.st_transform(NEW.geom_4326, :localSrid);
  END IF ;
  IF (NEW.geom_point_4326 IS NULL) THEN
    NEW.geom_point_4326 = public.st_pointonsurface(NEW.geom_4326);
  END IF ;
  IF (NEW."area" IS NULL) THEN
    NEW."area" = public.st_area(NEW.geom_local);
  END IF ;
  RETURN NEW;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100 ;

-----------------------------------------------------------------------
-- Fonction Trigger: actualisation champ geom_local et surface
-----------------------------------------------------------------------

CREATE OR REPLACE FUNCTION pr_priority_flora.edit_ap()
  RETURNS trigger AS
$BODY$
BEGIN
  IF (NEW.geom_local IS NULL) THEN
    NEW.geom_local = public.st_transform(NEW.geom_4326, :localSrid);
  END IF ;
  IF (NEW.geom_point_4326 IS NULL) THEN
    NEW.geom_point_4326 = public.st_pointonsurface(NEW.geom_4326);
  END IF ;
  IF (NEW."area" IS NULL) THEN
    NEW."area" = public.st_area(NEW.geom_local);
  END IF ;
  RETURN NEW;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
```

**Comment by LeaCBNA** [comment]
On a vérifié et tout fonctionne à part l'export au niveau des ZP qui semble tjs buggé "Internal server error". Sinon c'est top on arrive à saisir confortablement avec les GPX !  Et les ZP en forme de points sont redevenues normales, donc la consultation est ok aussi.

**Comment by jpm-cbna** [comment]
Concernant le bug de l'export affichant "`Internal server error`", il a lieu au au niveau de la liste des ZP que si le filtre "`Organisme`" est utilisé.
