### ISSUE TITLE
Ajout des champs géométrie des ZP et AP à l'export CSV

### ISSUE THREAD

**Issue by LeaCBNA** [PnX-SI/gn_module_flore_prioritaire#34]
Intégrer le champ MULTIPOLYGON dans les exports pour pouvoir importer le tout sous QGIS. Problème remonté par Véronique, il ne semble pas y avoir de champ de géométrie dans les exports (du moins pas au niveau de la liste des ZP), ou alors je suis pas placée au bon endroit ?

**Comment by jpm-cbna** [comment]
Les champs géométries de l'AP et de la ZP sont bien abscent. Il faut les ajouter.

**Comment by jpm-cbna** [comment]
Fermé par le commit f69e97b.
