### ISSUE TITLE
Trigger vers Synthèse

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_flore_prioritaire#4]
Mettre en place les triggers (Insert, Update et Delete) où chaque AP est une occurrence dans la synthèse.

**Comment by camillemonchicourt** [comment]
- Une AP est une ligne dans la Synthèse (une occurrence)
- Certaines infos sont récupérées au niveau de la ZP (date, dataset, cd_nom...)

**Comment by richardvergely** [comment]
Conçu avec l'aide des triggers de flore_patri v1 vers synthèse v2 : https://github.com/PnX-SI/GeoNature/blob/develop/data/migrations/v1tov2/florepatri.sql

**Comment by camillemonchicourt** [comment]
Commit ici : https://github.com/PnX-SI/gn_module_flore_prioritaire/commit/3cccfb3926aab811ab5ea3bef945b87e83489d33

**Comment by camillemonchicourt** [comment]
Triggers à relire par @gildeluermoz et @TheoLechemia 

Tu créées un CA mais sans nom ? Idem pour la source, il faut lui mettre un nom. 
Attention non compatible avec la branche ``develop`` actuelle de GeoNature. Par exemple dans la table des JDD, il n'y a plus le champs ``default_validity`` mais un nouveau champs ``validable``

**Comment by jpm-cbna** [comment]
Fait dans le commit 96605159d298be84d56a892a9912852c509d8634.
Piste d'amélioration : faire en sorte que le trigger puisse être relancer sans nécessité d'ajouter à nouveau les ZP et AP. Un simple update de chaque ligne dans la table des AP devrait permettre l'insertion ou la mise à jour dans la table `synthese`.
