### ISSUE TITLE
t_zprospect / Champs à supprimer

### ISSUE THREAD

**Issue by camillemonchicourt** [PnX-SI/gn_module_flore_prioritaire#6]
``id_history_action`` et ``id_validation`` n'ont pas à être présent dans la table. 
https://github.com/PnX-SI/gn_module_flore_prioritaire/blob/develop/data/FP.sql#L145

Ces tables transversales s'appuient sur l'UUID de l'objet. 

Du coup, pas sur qu'il doive y avoir un UUID SINP au niveau de la ZP. Car l'occurrence est l'AP. C'est cet UUID qui sera utilisé et est à renommer unique_id_sinp_ap.
Celui de la ZP pourrait être utile si on faisait de la partie de la ZP sans AP, une occurrence d'absence dans la Synthèse. Pas souhaitable à priori. Mais garder le champs ``unique_id_sinp_zp`` néanmoins.

**Comment by camillemonchicourt** [comment]
Supprimer ``srid_design`` ?
Le champs ``geom_local`` a un srid local fixe donc pas besoin. 
Le SRID de geom_local ne devrait pas être en dur dans le fichier mais remplacer par le SRID en paramètre lors de l'installation

**Comment by richardvergely** [comment]
Ok pour les UUID et le srid_design
